### ISSUE TITLE
pip install in readme out of date

### ISSUE THREAD

**Issue by jordanmmck** [hyperledger/aries-acapy-plugin-toolbox#44] opened 2020-12-15 22:39 UTC
I'm trying to run the toolbox locally and when I run this command:

```
pip install git+https://github.com/hyperledger/aries-acapy-plugin-toolbox.git@master#egg=acapy-plugin-toolbox
```

I get this error:

```
no matches found: git+https://github.com/hyperledger/aries-acapy-plugin-toolbox.git@master#egg=acapy-plugin-toolbox
```

Is this URL out of date? Command is from the readme, here:

https://github.com/hyperledger/aries-acapy-plugin-toolbox#plugin-installation

**Comment by dbluhm** [comment] 2020-12-15 22:50
Thanks for pointing this out! With the version of pip installed on my system, it is able to find the intended package but it did emit the following:

```
WARNING: Generating metadata for package acapy-plugin-toolbox produced metadata for project name aries-acapy-plugin-toolbox. Fix your #egg=acapy-plugin-toolbox fragments.
```

The README is due an update but in the meantime correcting the command to:
```
pip install git+https://github.com/hyperledger/aries-acapy-plugin-toolbox.git@master#egg=acapy_plugin_toolbox
```
seems to do the trick (Note the underscores instead of dashes).

**Comment by jordanmmck** [comment] 2020-12-15 22:59
Thanks for the response. Unfortunately I'm getting the same error with that command.

I'm not sure if this is related, but I'm also getting some pip dependency version conflicts when I do `pip install -e .` in the acapy repo. If I just run that `pip install` I get:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aries-acapy-plugin-toolbox 0.1.0 requires marshmallow==3.0.0, but you have marshmallow 3.5.1 which is incompatible.
```

But then if I do `pip install marshmallow==3.0.0` I get:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aries-cloudagent 0.6.0rc0 requires marshmallow==3.5.1, but you have marshmallow 3.0.0 which is incompatible.
```

So there seems to be a dep conflict?

**Comment by dbluhm** [comment] 2020-12-15 23:17
Hm. Despite the warning of incompatibility, I think the toolbox plugin should be working with either version of marshmallow. I have seen this error while switching between different ACA-Py versions but have largely ignored them (from what I remember at least) with no adverse side effects.

What versions of python and pip are you using? OS and any other details you feel might be relevant would be helpful as well. I'm not terribly familiar with the nuances of pip git repo support but given that dropping the egg fixed it seems to indicate that might have been the cause of your earlier problem.

While on the subject of deficiencies of the README as it stands and noticing the version mentioned in that error, I'll take the opportunity to also let you know that the most recent version of ACA-Py currently supported by the toolbox plugin is 0.5.3. I'm actively working to address this and we should have a release supporting 0.6.0 once the ACA-Py team pushes it. This dependency issue should also be resolved at that point as the toolbox plugin will be updated to match ACA-Py's. If you're interested, you can follow that line of development here: https://github.com/dbluhm/aries-acapy-plugin-toolbox/tree/update/aca-py-0.6.0rc0

**Comment by jordanmmck** [comment] 2020-12-16 01:06
I got it to run using your 6.0rc branch. Thanks for the help!

**Comment by frostyfrog** [comment] 2021-12-07 18:16
Based upon the last response, and the fact that this issue was last commented on nearly a year ago, I will be closing this issue.

**Closed by frostyfrog** 2021-12-07 18:16 UTC
